# Generated by Django 4.2.17 on 2025-03-07 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SolarAI", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BinaryImageModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("image_data", models.ImageField(upload_to="plots/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
